### ISSUE TITLE
デバイス連携のためのAPI作成

### ISSUE THREAD

**Issue by Prokuma** [yurupro/Mesistant#2]
デバイスの連携のためのAPIがないからchecker.pyの作業をこれ以上進めない
定義だけでもいいから仕様を決定してほしい

**Comment by rkun123** [comment]
https://github.com/yurupro/Mesistant/blob/dev/recipe.go#L30-L40
とりあえずレシピのアップロードは実装したよ

**Comment by rkun123** [comment]
デバイスとユーザーの紐づけ、どうしましょう

**Comment by rkun123** [comment]
デバイスの登録
```
/device/register
{
    "user_id": "{USER_ID}"
}
```
デバイスにあるキューの取得
/device/:id/queue

**Comment by rkun123** [comment]
![Screenshot from 2019-08-15 11-34-58](https://user-images.githubusercontent.com/12907598/63069148-cb438700-bf50-11e9-9233-56062d93e7c1.png)
